sm_2/sm_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('webapp.urls')),

]

sm_2/webapp/urls.py
from django.urls import path

from .views import (
    ContentListView,
    create_content,
    delete_content,
    ContentUpdateView
)

app_name = 'webapp'


urlpatterns = [
    path('', ContentListView.as_view(), name='content-list'),
    path('/create', create_content, name='create-content'),
    path('/delete', delete_content, name='delete-content'),
    path('/update/<int:pk>', ContentUpdateView.as_view(), name='update-content'),
]

sm_2/webapp/models.py
from django.db import models


class Content(models.Model):
    content_id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=500, null=False, blank=False)
    name_content = models.CharField(max_length=500, null=False, blank=False)
    resource = models.CharField(max_length=255, null=False, blank=False)
    id_format_content = models.PositiveIntegerField()
    url = models.CharField(max_length=500)
    success = models.IntegerField()
    success_data_update = models.IntegerField()
    acc_type = models.PositiveIntegerField()
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'content'
        managed = False


# Create your models here.

sm_2/webapp/forms.py
from django import forms
from .models import Content


class ContentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ContentForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'style': 'width: 300px;'})

    class Meta:
        model = Content
        exclude = ('created_at',)

sm_2/webapp/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import FormMixin, UpdateView

from .models import Content
from .forms import ContentForm


class ContentListView(ListView, FormMixin):
    model = Content
    context_object_name = 'contents'
    template_name = 'content/index.html'
    form_class = ContentForm
    ordering = '-created_at'
    paginate_by = 500
    paginate_orphans = 10

    def get_queryset(self):
        return Content.objects.using('metrics').all()[:10]


def create_content(request, *args, **kwargs):
    if request.is_ajax and request.method == "POST":
        data = request.POST
        content = Content.objects.using('metrics').create(
            project_name=data.get("project_name"),
            name_content=data.get('name_content'),
            resource=data.get('resource'),
            id_format_content=data.get('id_format_content'),
            url=data.get('url'),
            success=data.get('success'),
            success_data_update=data.get('success_data_update'),
            acc_type=data.get('acc_type')
        )
        return JsonResponse({'message': f'content "{content.name_content}" is created successfully'}, status=200)
    return JsonResponse({"error": "something went wrong..."}, status=400, safe=False)


def delete_content(request, *args, **kwargs):
    if request.is_ajax and request.method == 'POST':
        content = Content.objects.using('metrics').get(content_id=list(dict(request.POST).keys())[0])
        content.delete()
        return JsonResponse({'message': f'content "{content.name_content}" is deleted successfully'}, status=200)
    return JsonResponse({"error": "something went wrong..."}, status=400, safe=False)


class ContentUpdateView(UpdateView):
    model = Content
    form_class = ContentForm

    def get(self, request, *args, **kwargs):
        content = Content.objects.using('metrics').get(content_id=kwargs.get('pk'))
        form = ContentForm(instance=content)
        return HttpResponse(form.as_p())

    def post(self, request, *args, **kwargs):
        data = request.POST
        if request.is_ajax:
            content = Content.objects.using('metrics').get(content_id=kwargs.get('pk'))
            content.project_name = data.get("project_name")
            content.name_content = data.get('name_content')
            content.resource = data.get('resource')
            content.id_format_content = int(data.get('id_format_content')[0])
            content.url = data.get('url')
            content.success = int(data.get('success')[0])
            content.success_data_update = int(data.get('success_data_update')[0])
            content.acc_type = int(data.get('acc_type')[0])
            content.save()
            return JsonResponse({'message': f'content "{content.name_content}" is updated successfully'})
        return JsonResponse({"error": "something went wrong..."}, status=400, safe=False)

sm_2/webapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4922259a88.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>


</head>

<body class="global-body">
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webapp:content-list' %}">

      home
    </a>
  </div>
</nav>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

sm_2/webapp/templates/content/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="mt-3 d-flex justify-content-between">
        <span class="col-md-6">Content list</span>
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#createModal">+ add new</button>
    </div>

    <div class="mt-5 w-100">
        {% if contents %}
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">action</th>
                        <th scope="col">id</th>
                        <th scope="col">project name</th>
                        <th scope="col">content name</th>
                        <th scope="col">resource</th>
                        <th scope="col">id_format_content</th>
                        <th scope="col">url</th>
                        <th scope="col">success</th>
                        <th scope="col">success data update</th>
                        <th scope="col">acc_type</th>
                        <th scope="col">created at</th>
                    </tr>
                </thead>
            <tbody>
            <button hidden id="openUpdateFormModel" type="button" data-bs-toggle="modal" data-bs-target="#updateModal"></button>
            {% for content in contents.all %}
                <tr>
                    <th scope="row" role="group">
                        <div id="{{ content.content_id }}" data-deleteurl="{% url 'webapp:delete-content' %}" class="btn-group">
                            <button onclick="deleteContent(event)" class="btn btn-danger">delete</button>
                            <button data-updateurl="{% url 'webapp:update-content' content.content_id %}" onclick="getUpdateForm(event)"
                                    class="btn btn-secondary">edit</button>
                        </div>
                    </th>
                    <th scope="row">{{ content.content_id }}</th>
                    <td>{{ content.project_name }}</td>
                    <td>{{ content.name_content }}</td>
                    <td>{{ content.resource }}</td>
                    <td>{{ content.id_format_content }}</td>
                    <td>{{ content.url }}</td>
                    <td>{{ content.success }}</td>
                    <td>{{ content.success_data_update }}</td>
                    <td>{{ content.acc_type }}</td>
                    <td>{{ content.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        <!-- Row end -->

        {% else %}
        <p>No content</p>
        {% endif %}

    </div>

      <!-- Modal to create -->
      <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="createModalLabel">Add new row to "content" table</h5>
              <button id="closeCreateModal" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div data-targeturl="{% url 'webapp:create-content'  %}" id="createForm">{% include 'partial/content_form.html' %}</div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">close</button>
              <button type="button" onclick="createContent(event)" class="btn btn-warning">add</button>
            </div>
          </div>
        </div>
      </div>
    <!-- end modal create -->


      <!-- Modal to update -->
      <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="updateModalLabel"></h5>
              <button id="closeUpdateModal" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="updateForm"></form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">close</button>
              <button type="button" onclick="updateContent(event)" class="btn btn-warning">update</button>
            </div>
          </div>
        </div>
      </div>
    <!-- end modal update -->
{% include 'partial/paginate.html' %}
{% endblock content %}

sm_2/webapp/templates/partial/content_form.html
{% if not fields_only %}
        <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}" class="form-inline justify-content-center">
            <div class="form-group">
                {% csrf_token %}
            {% endif %}
                {% for error in form.non_field_errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}
                {% for field in form %}
                    <div class="form-group d-flex justify-content-between">
                    <p><label class="mt-3 text-secondary text-uppercase" for="{{ field.id_for_label }}">{{ field.label }}:</label></p>

                   {% for error in field.errors %}
                       <p class="form-error">{{ error }}</p>
                   {% endfor %}
                   <p {% if field.errors %} class="form-field-error"{% endif %}>{{ field }}</p>
                    <br>
                    </div>
                {% endfor %}
            {% if not fields_only %}
                <br/>
             </div>
            </form>


{% endif %}

sm_2/webapp/templates/partial/paginate.html
<div class="d-flex justify-content-center ">
<ul class="pagination justify-content-center pagination-sm update-profile">
        {% if page_obj.has_previous %}
            <li class="page-item d-flex" >
            <a class="paginate-btn paginate-left" href="?{% if query %}{{ query }}&{% endif %}page=1" tabindex="-1">&laquo; start</a>
            <a class="paginate-btn"  href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">prev</a>
            </li>
        {% else %}
            <li class="page-item disabled d-flex">
            <a class="paginate-btn paginate-left" href="#" tabindex="-1" aria-disabled="true">Start</a>
            <a class="paginate-btn" href="#" tabindex="-1" aria-disabled="true">End</a>
            <li>
        {% endif %}
    <li>
        <form style="width: 60px;" method="get">
            {% if search_value %}<input type="hidden" name="search" value="{{ search_value }}">{% endif %}
             <input class="paginate-input" placeholder="page" type="text" name="page" id="page" value="{{ page_obj.number }}">
        </form>
    </li>
        {% if page_obj.has_next %}
            <li class="page-item d-flex">
            <a class="paginate-btn"  href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">next</a>
            <a class="paginate-btn paginate-right" href="?{% if query %}{{ query }}&{% endif %}page={{ paginator.num_pages }}">end &raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled d-flex">
            <a class="paginate-btn" href="#" tabindex="-1" aria-disabled="true">next</a>
            <a class="paginate-btn paginate-right" href="#" tabindex="-1" aria-disabled="true">end &raquo;</a>
            </li>
        {% endif %}
</ul>
</div>